// packages/model/src/thevie/lora_evolution.js
// LoraEvo — Guide Intelligent & Auto-Évolutif
// Connecté à T369Inference + LoRA Training réel (forward/backward Adam)
// SkyAInet × Thevie × Nikola T369

"use strict";

import { Dilithium5Signer }              from '#dilithium';
import { LoraAdapter, crossEntropyGrad } from '#lora_trainer';
import { writeFile, mkdir }              from 'fs/promises';

// ─────────────────────────────────────────────────────────────────
// CONSTANTES
// ─────────────────────────────────────────────────────────────────

const STM_MAX           = 40;   // taille max mémoire court-terme
const LTM_MAX           = 25;   // taille max mémoire long-terme
const LTM_MIN_CHARS     = 120;  // longueur min pour archivage long-terme
const EVOLVE_EVERY      = 15;   // interactions entre chaque boost d'évolution
const EVOLVE_BOOST      = 0.009;
const MIN_LESSONS_TRAIN = 8;
const LOSS_STAGNATION   = 0.98; // early stopping : amélioration < 2 %
const CHECKPOINT_DIR    = './checkpoints';

// ─────────────────────────────────────────────────────────────────
// SPÉCIALISATIONS — détection par mots-clés + compteurs d'exposition
// ─────────────────────────────────────────────────────────────────

const SPECIALIZATIONS = [
  { name: 'Technique & Programmation', keys: ['code','rust','python','javascript','bug','function','algorithm','technique','debug'] },
  { name: 'Éthique & Philosophie',     keys: ['éthique','ethique','philosoph','moral','valeur','justice','liberté','conscience'] },
  { name: 'Créativité & Imagination',  keys: ['créatif','creatif','rêve','reve','histoire','poème','art','imagin','fiction'] },
  { name: 'Science & Données',         keys: ['science','données','data','statistique','recherche','analyse','modèle','neural'] },
  { name: 'Guide Polyvalent',          keys: [] },  // défaut
];

/** Détecte la spécialisation la plus pertinente pour un prompt */
function detectSpecialization(prompt, exposures) {
  const lower = prompt.toLowerCase();
  let   best  = SPECIALIZATIONS[SPECIALIZATIONS.length - 1];
  let   bestScore = 0;

  for (const spec of SPECIALIZATIONS) {
    const hits = spec.keys.filter(k => lower.includes(k)).length;
    // Pondère par l'exposition cumulée (renforcement progressif)
    const score = hits + (exposures.get(spec.name) ?? 0) * 0.1;
    if (score > bestScore) { bestScore = score; best = spec; }
  }
  return best.name;
}

// ─────────────────────────────────────────────────────────────────
// PROFIL D'ÉVOLUTION
// ─────────────────────────────────────────────────────────────────

export class EvolutionProfile {
  constructor() {
    this.ethics        = 0.82;
    this.technical     = 0.75;
    this.creativity    = 0.78;
    this.wisdom        = 0.80;
    this.userAlignment = 0.85;
  }

  /** Met à jour les dimensions selon le type de spécialisation courant */
  adapt(specialization) {
    switch (specialization) {
      case 'Technique & Programmation':
        this.technical     = Math.min(0.99, this.technical     + 0.005);
        this.wisdom        = Math.min(0.99, this.wisdom        + 0.002);
        break;
      case 'Éthique & Philosophie':
        this.ethics        = Math.min(0.99, this.ethics        + 0.005);
        this.wisdom        = Math.min(0.99, this.wisdom        + 0.004);
        break;
      case 'Créativité & Imagination':
        this.creativity    = Math.min(0.99, this.creativity    + 0.006);
        this.userAlignment = Math.min(0.99, this.userAlignment + 0.002);
        break;
      case 'Science & Données':
        this.technical     = Math.min(0.99, this.technical     + 0.004);
        this.wisdom        = Math.min(0.99, this.wisdom        + 0.003);
        break;
      default:
        this.userAlignment = Math.min(0.99, this.userAlignment + 0.003);
    }
  }

  toJSON() {
    return {
      ethics: +this.ethics.toFixed(4),       technical  : +this.technical.toFixed(4),
      creativity: +this.creativity.toFixed(4), wisdom    : +this.wisdom.toFixed(4),
      userAlignment: +this.userAlignment.toFixed(4),
    };
  }
}

// ─────────────────────────────────────────────────────────────────
// LORA EVO
// ─────────────────────────────────────────────────────────────────

// ═══════════════════════════════════════════════════════════════
// SMART CONTRACT TEMPLATES — Solidity
// Chaque template utilise {{PARAM}} pour l'interpolation.
// ═══════════════════════════════════════════════════════════════

const SC_TEMPLATES = Object.freeze({

  ERC20: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
{{#if pausable}}import "@openzeppelin/contracts/security/Pausable.sol";{{/if}}

/**
 * @title {{tokenName}}
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      Tax: {{taxPercent}}% | Vesting: {{vestingMonths}} months | Supply: {{totalSupply}}
 */
contract {{tokenName}} is ERC20, Ownable {
    uint256 public constant TOTAL_SUPPLY = {{totalSupply}} * 10 ** 18;
    uint256 public taxPercent = {{taxPercent}};
    address public treasury;

    // Vesting
    mapping(address => uint256) public vestingStart;
    mapping(address => uint256) public vestingAmount;
    uint256 public vestingDuration = {{vestingMonths}} * 30 days;

    event TaxCollected(address indexed from, uint256 amount);
    event VestingGranted(address indexed beneficiary, uint256 amount);

    constructor(address _treasury) ERC20("{{tokenName}}", "{{tokenSymbol}}") Ownable(msg.sender) {
        treasury = _treasury;
        _mint(msg.sender, TOTAL_SUPPLY);
    }

    function _transfer(address from, address to, uint256 amount) internal override {
        if (taxPercent > 0 && from != owner() && to != owner()) {
            uint256 tax = (amount * taxPercent) / 100;
            super._transfer(from, treasury, tax);
            emit TaxCollected(from, tax);
            amount -= tax;
        }
        super._transfer(from, to, amount);
    }

    function grantVesting(address beneficiary, uint256 amount) external onlyOwner {
        require(balanceOf(owner()) >= amount, "Insufficient balance");
        vestingStart[beneficiary]  = block.timestamp;
        vestingAmount[beneficiary] = amount;
        _transfer(owner(), address(this), amount);
        emit VestingGranted(beneficiary, amount);
    }

    function claimVested() external {
        uint256 elapsed   = block.timestamp - vestingStart[msg.sender];
        uint256 claimable = (vestingAmount[msg.sender] * elapsed) / vestingDuration;
        require(claimable > 0, "Nothing to claim yet");
        vestingAmount[msg.sender] -= claimable;
        _transfer(address(this), msg.sender, claimable);
    }

    function setTax(uint256 _taxPercent) external onlyOwner {
        require(_taxPercent <= 25, "Tax cannot exceed 25%");
        taxPercent = _taxPercent;
    }

    function setTreasury(address _treasury) external onlyOwner {
        treasury = _treasury;
    }
}`,

  NFT: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/interfaces/IERC2981.sol";

/**
 * @title {{tokenName}} NFT
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      Royalties: {{royaltyPercent}}%
 */
contract {{tokenName}} is ERC721URIStorage, Ownable, IERC2981 {
    uint256 private _tokenIds;
    uint256 public mintPrice = 0.01 ether;
    uint96  public royaltyFee = {{royaltyPercent}} * 100; // basis points
    address public royaltyReceiver;
    mapping(address => bool) public whitelist;
    bool public whitelistOnly = {{whitelist}};

    event Minted(address indexed to, uint256 tokenId, string uri);

    constructor() ERC721("{{tokenName}}", "{{tokenSymbol}}") Ownable(msg.sender) {
        royaltyReceiver = msg.sender;
    }

    function mint(address to, string memory tokenURI) external payable returns (uint256) {
        if (whitelistOnly) require(whitelist[msg.sender], "Not whitelisted");
        require(msg.value >= mintPrice, "Insufficient payment");
        _tokenIds++;
        uint256 newId = _tokenIds;
        _safeMint(to, newId);
        _setTokenURI(newId, tokenURI);
        emit Minted(to, newId, tokenURI);
        return newId;
    }

    function royaltyInfo(uint256, uint256 salePrice) external view override returns (address, uint256) {
        return (royaltyReceiver, (salePrice * royaltyFee) / 10_000);
    }

    function addToWhitelist(address[] calldata addresses) external onlyOwner {
        for (uint i = 0; i < addresses.length; i++) whitelist[addresses[i]] = true;
    }

    function withdraw() external onlyOwner {
        payable(owner()).transfer(address(this).balance);
    }

    function supportsInterface(bytes4 id) public view override(ERC721URIStorage, IERC165) returns (bool) {
        return id == type(IERC2981).interfaceId || super.supportsInterface(id);
    }
}`,

  DAO: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/governance/Governor.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorVotes.sol";
import "@openzeppelin/contracts/governance/extensions/GovernorTimelockControl.sol";

/**
 * @title {{contractName}} DAO
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      Quorum: {{quorumPercent}}%
 */
contract {{contractName}} is Governor, GovernorVotes, GovernorTimelockControl {
    uint256 public constant QUORUM_PERCENT = {{quorumPercent}};
    uint256 public votingDelay_   = 1;        // 1 block
    uint256 public votingPeriod_  = 50400;    // ~1 week
    uint256 public proposalThreshold_ = 1e18; // 1 token minimum

    constructor(IVotes _token, TimelockController _timelock)
        Governor("{{contractName}}")
        GovernorVotes(_token)
        GovernorTimelockControl(_timelock) {}

    function votingDelay() public view override returns (uint256) { return votingDelay_; }
    function votingPeriod() public view override returns (uint256) { return votingPeriod_; }
    function proposalThreshold() public view override returns (uint256) { return proposalThreshold_; }

    function quorum(uint256 blockNumber) public view override returns (uint256) {
        return (token().getPastTotalSupply(blockNumber) * QUORUM_PERCENT) / 100;
    }

    function state(uint256 proposalId) public view override(Governor, GovernorTimelockControl) returns (ProposalState) {
        return super.state(proposalId);
    }

    function _execute(uint256 proposalId, address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash)
        internal override(Governor, GovernorTimelockControl) {
        super._execute(proposalId, targets, values, calldatas, descriptionHash);
    }

    function _cancel(address[] memory targets, uint256[] memory values, bytes[] memory calldatas, bytes32 descriptionHash)
        internal override(Governor, GovernorTimelockControl) returns (uint256) {
        return super._cancel(targets, values, calldatas, descriptionHash);
    }

    function _executor() internal view override(Governor, GovernorTimelockControl) returns (address) {
        return super._executor();
    }

    function supportsInterface(bytes4 interfaceId) public view override(Governor, GovernorTimelockControl) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}`,

  VESTING: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title {{contractName}} Vesting
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      Duration: {{vestingMonths}} months
 */
contract {{contractName}} is Ownable, ReentrancyGuard {
    IERC20 public token;
    uint256 public vestingDuration = {{vestingMonths}} * 30 days;

    struct VestingSchedule {
        uint256 totalAmount;
        uint256 startTime;
        uint256 cliffDuration;
        uint256 released;
        bool    revocable;
        bool    revoked;
    }

    mapping(address => VestingSchedule) public schedules;
    address[] public beneficiaries;

    event VestingCreated(address indexed beneficiary, uint256 amount, uint256 cliff);
    event TokensReleased(address indexed beneficiary, uint256 amount);
    event VestingRevoked(address indexed beneficiary);

    constructor(address _token) Ownable(msg.sender) {
        token = IERC20(_token);
    }

    function createVesting(address beneficiary, uint256 amount, uint256 cliffMonths, bool revocable) external onlyOwner {
        require(schedules[beneficiary].totalAmount == 0, "Vesting already exists");
        require(token.transferFrom(msg.sender, address(this), amount), "Transfer failed");
        schedules[beneficiary] = VestingSchedule({
            totalAmount   : amount,
            startTime     : block.timestamp,
            cliffDuration : cliffMonths * 30 days,
            released      : 0,
            revocable     : revocable,
            revoked       : false
        });
        beneficiaries.push(beneficiary);
        emit VestingCreated(beneficiary, amount, cliffMonths);
    }

    function release() external nonReentrant {
        VestingSchedule storage s = schedules[msg.sender];
        require(!s.revoked, "Vesting revoked");
        uint256 releasable = _computeReleasable(s);
        require(releasable > 0, "Nothing to release");
        s.released += releasable;
        require(token.transfer(msg.sender, releasable), "Transfer failed");
        emit TokensReleased(msg.sender, releasable);
    }

    function revoke(address beneficiary) external onlyOwner {
        VestingSchedule storage s = schedules[beneficiary];
        require(s.revocable, "Not revocable");
        require(!s.revoked, "Already revoked");
        uint256 refund = s.totalAmount - s.released - _computeReleasable(s);
        s.revoked = true;
        if (refund > 0) require(token.transfer(owner(), refund), "Refund failed");
        emit VestingRevoked(beneficiary);
    }

    function _computeReleasable(VestingSchedule storage s) internal view returns (uint256) {
        if (block.timestamp < s.startTime + s.cliffDuration) return 0;
        uint256 elapsed  = block.timestamp - s.startTime;
        uint256 vested   = elapsed >= vestingDuration
            ? s.totalAmount
            : (s.totalAmount * elapsed) / vestingDuration;
        return vested - s.released;
    }
}`,

  STAKING: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

/**
 * @title {{contractName}} Staking
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      APY: {{apyPercent}}%
 */
contract {{contractName}} is Ownable, ReentrancyGuard {
    IERC20 public stakingToken;
    IERC20 public rewardToken;
    uint256 public apyPercent = {{apyPercent}};
    uint256 public constant SECONDS_PER_YEAR = 365 days;

    struct StakeInfo {
        uint256 amount;
        uint256 since;
        uint256 rewardDebt;
    }

    mapping(address => StakeInfo) public stakes;
    uint256 public totalStaked;

    event Staked(address indexed user, uint256 amount);
    event Unstaked(address indexed user, uint256 amount);
    event RewardClaimed(address indexed user, uint256 reward);

    constructor(address _stakingToken, address _rewardToken) Ownable(msg.sender) {
        stakingToken = IERC20(_stakingToken);
        rewardToken  = IERC20(_rewardToken);
    }

    function stake(uint256 amount) external nonReentrant {
        require(amount > 0, "Cannot stake 0");
        _claimReward(msg.sender);
        require(stakingToken.transferFrom(msg.sender, address(this), amount));
        stakes[msg.sender].amount += amount;
        stakes[msg.sender].since   = block.timestamp;
        totalStaked += amount;
        emit Staked(msg.sender, amount);
    }

    function unstake(uint256 amount) external nonReentrant {
        require(stakes[msg.sender].amount >= amount, "Insufficient stake");
        _claimReward(msg.sender);
        stakes[msg.sender].amount -= amount;
        totalStaked -= amount;
        require(stakingToken.transfer(msg.sender, amount));
        emit Unstaked(msg.sender, amount);
    }

    function claimReward() external nonReentrant {
        _claimReward(msg.sender);
    }

    function _claimReward(address user) internal {
        uint256 pending = pendingReward(user);
        if (pending > 0) {
            stakes[user].since = block.timestamp;
            stakes[user].rewardDebt = 0;
            require(rewardToken.transfer(user, pending));
            emit RewardClaimed(user, pending);
        } else {
            stakes[user].since = block.timestamp;
        }
    }

    function pendingReward(address user) public view returns (uint256) {
        StakeInfo memory s = stakes[user];
        if (s.amount == 0) return 0;
        uint256 duration = block.timestamp - s.since;
        return (s.amount * apyPercent * duration) / (100 * SECONDS_PER_YEAR);
    }

    function setApy(uint256 _apy) external onlyOwner {
        require(_apy <= 10000, "APY too high");
        apyPercent = _apy;
    }
}`,

  MARKETPLACE: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/IERC721.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title {{contractName}} NFT Marketplace
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 */
contract {{contractName}} is ReentrancyGuard, Ownable {
    uint256 public platformFee = {{taxPercent}} * 100; // basis points
    uint256 private _listingIds;

    struct Listing {
        uint256 id;
        address seller;
        address nftContract;
        uint256 tokenId;
        uint256 price;
        bool    active;
    }

    mapping(uint256 => Listing) public listings;
    mapping(address => uint256) public pendingWithdrawals;

    event Listed(uint256 indexed listingId, address indexed seller, address nft, uint256 tokenId, uint256 price);
    event Sold(uint256 indexed listingId, address indexed buyer, uint256 price);
    event Delisted(uint256 indexed listingId);

    constructor() Ownable(msg.sender) {}

    function list(address nftContract, uint256 tokenId, uint256 price) external returns (uint256) {
        require(price > 0, "Price must be > 0");
        IERC721(nftContract).transferFrom(msg.sender, address(this), tokenId);
        _listingIds++;
        listings[_listingIds] = Listing(_listingIds, msg.sender, nftContract, tokenId, price, true);
        emit Listed(_listingIds, msg.sender, nftContract, tokenId, price);
        return _listingIds;
    }

    function buy(uint256 listingId) external payable nonReentrant {
        Listing storage l = listings[listingId];
        require(l.active, "Not active");
        require(msg.value >= l.price, "Insufficient ETH");
        l.active = false;
        uint256 fee      = (l.price * platformFee) / 10_000;
        uint256 proceeds = l.price - fee;
        pendingWithdrawals[owner()]    += fee;
        pendingWithdrawals[l.seller]   += proceeds;
        IERC721(l.nftContract).transferFrom(address(this), msg.sender, l.tokenId);
        emit Sold(listingId, msg.sender, l.price);
        if (msg.value > l.price) payable(msg.sender).transfer(msg.value - l.price);
    }

    function delist(uint256 listingId) external nonReentrant {
        Listing storage l = listings[listingId];
        require(l.seller == msg.sender, "Not seller");
        require(l.active, "Already inactive");
        l.active = false;
        IERC721(l.nftContract).transferFrom(address(this), msg.sender, l.tokenId);
        emit Delisted(listingId);
    }

    function withdraw() external nonReentrant {
        uint256 amount = pendingWithdrawals[msg.sender];
        require(amount > 0, "Nothing to withdraw");
        pendingWithdrawals[msg.sender] = 0;
        payable(msg.sender).transfer(amount);
    }
}`,

  MULTISIG: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title {{contractName}} MultiSig Wallet
 * @notice {{description}}
 * @dev Generated by LoraEvo — SkyAInet Sovereign AI
 *      Required signatures: {{signaturesRequired}} / {{totalSigners}}
 */
contract {{contractName}} {
    address[] public owners;
    uint256 public required;
    mapping(address => bool) public isOwner;

    struct Transaction {
        address to;
        uint256 value;
        bytes   data;
        bool    executed;
        uint256 confirmations;
    }

    Transaction[] public transactions;
    mapping(uint256 => mapping(address => bool)) public confirmed;

    event Deposit(address indexed sender, uint256 value);
    event Submitted(uint256 indexed txId);
    event Confirmed(address indexed owner, uint256 indexed txId);
    event Executed(uint256 indexed txId);
    event Revoked(address indexed owner, uint256 indexed txId);

    modifier onlyOwner()        { require(isOwner[msg.sender], "Not owner"); _; }
    modifier txExists(uint id)  { require(id < transactions.length, "Tx not found"); _; }
    modifier notExecuted(uint id) { require(!transactions[id].executed, "Already executed"); _; }
    modifier notConfirmed(uint id){ require(!confirmed[id][msg.sender], "Already confirmed"); _; }

    constructor(address[] memory _owners, uint256 _required) {
        require(_owners.length > 0, "No owners");
        require(_required > 0 && _required <= _owners.length, "Invalid required");
        for (uint i = 0; i < _owners.length; i++) {
            require(!isOwner[_owners[i]], "Duplicate owner");
            isOwner[_owners[i]] = true;
            owners.push(_owners[i]);
        }
        required = _required;
    }

    receive() external payable { emit Deposit(msg.sender, msg.value); }

    function submit(address to, uint256 value, bytes calldata data) external onlyOwner returns (uint256) {
        transactions.push(Transaction(to, value, data, false, 0));
        uint256 txId = transactions.length - 1;
        emit Submitted(txId);
        return txId;
    }

    function confirm(uint256 txId) external onlyOwner txExists(txId) notExecuted(txId) notConfirmed(txId) {
        confirmed[txId][msg.sender] = true;
        transactions[txId].confirmations++;
        emit Confirmed(msg.sender, txId);
    }

    function execute(uint256 txId) external txExists(txId) notExecuted(txId) {
        Transaction storage t = transactions[txId];
        require(t.confirmations >= required, "Insufficient confirmations");
        t.executed = true;
        (bool ok,) = t.to.call{value: t.value}(t.data);
        require(ok, "Execution failed");
        emit Executed(txId);
    }

    function revoke(uint256 txId) external onlyOwner txExists(txId) notExecuted(txId) {
        require(confirmed[txId][msg.sender], "Not confirmed");
        confirmed[txId][msg.sender] = false;
        transactions[txId].confirmations--;
        emit Revoked(msg.sender, txId);
    }

    function getOwners() external view returns (address[] memory) { return owners; }
    function getTransaction(uint256 txId) external view returns (address, uint256, bytes memory, bool, uint256) {
        Transaction storage t = transactions[txId];
        return (t.to, t.value, t.data, t.executed, t.confirmations);
    }
}`,
});

// ─── ABI simplifiés par type ──────────────────────────────────
const SC_ABI_TEMPLATES = Object.freeze({
  ERC20: [
    { name: 'transfer',       type: 'function', inputs: [{ name: 'to', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { name: 'approve',        type: 'function', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ type: 'bool' }] },
    { name: 'balanceOf',      type: 'function', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
    { name: 'totalSupply',    type: 'function', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
    { name: 'claimVested',    type: 'function', inputs: [], outputs: [] },
    { name: 'grantVesting',   type: 'function', inputs: [{ name: 'beneficiary', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [] },
    { name: 'setTax',         type: 'function', inputs: [{ name: 'percent', type: 'uint256' }], outputs: [] },
    { name: 'Transfer',       type: 'event',    inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'value', type: 'uint256' }] },
  ],
  NFT: [
    { name: 'mint',           type: 'function', inputs: [{ name: 'to', type: 'address' }, { name: 'tokenURI', type: 'string' }], outputs: [{ type: 'uint256' }] },
    { name: 'ownerOf',        type: 'function', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }], stateMutability: 'view' },
    { name: 'tokenURI',       type: 'function', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'string' }], stateMutability: 'view' },
    { name: 'royaltyInfo',    type: 'function', inputs: [{ name: 'tokenId', type: 'uint256' }, { name: 'salePrice', type: 'uint256' }], outputs: [{ type: 'address' }, { type: 'uint256' }], stateMutability: 'view' },
    { name: 'Transfer',       type: 'event',    inputs: [{ name: 'from', type: 'address', indexed: true }, { name: 'to', type: 'address', indexed: true }, { name: 'tokenId', type: 'uint256', indexed: true }] },
  ],
  STAKING: [
    { name: 'stake',          type: 'function', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
    { name: 'unstake',        type: 'function', inputs: [{ name: 'amount', type: 'uint256' }], outputs: [] },
    { name: 'claimReward',    type: 'function', inputs: [], outputs: [] },
    { name: 'pendingReward',  type: 'function', inputs: [{ name: 'user', type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
    { name: 'Staked',         type: 'event',    inputs: [{ name: 'user', type: 'address', indexed: true }, { name: 'amount', type: 'uint256' }] },
  ],
  MULTISIG: [
    { name: 'submit',         type: 'function', inputs: [{ name: 'to', type: 'address' }, { name: 'value', type: 'uint256' }, { name: 'data', type: 'bytes' }], outputs: [{ type: 'uint256' }] },
    { name: 'confirm',        type: 'function', inputs: [{ name: 'txId', type: 'uint256' }], outputs: [] },
    { name: 'execute',        type: 'function', inputs: [{ name: 'txId', type: 'uint256' }], outputs: [] },
    { name: 'revoke',         type: 'function', inputs: [{ name: 'txId', type: 'uint256' }], outputs: [] },
    { name: 'getOwners',      type: 'function', inputs: [], outputs: [{ type: 'address[]' }], stateMutability: 'view' },
    { name: 'Executed',       type: 'event',    inputs: [{ name: 'txId', type: 'uint256', indexed: true }] },
  ],
});

export class LoraEvo {
  // Champs privés
  #signer;
  #loraAdapter;       // LoraAdapter | null
  #trainingCount;
  #isTraining;
  #lossHistory;       // Float32Array ring buffer 32
  #exposures;         // Map<specialization, count> pour détection progressive
  #inferenceEngine;   // T369Inference | null
  #contracts;         // Map<contractId, GeneratedContract> — Smart Contracts générés
  #contractCount;     // compteur pour IDs uniques

  constructor() {
    this.modelName              = 'LoraEvo';
    this.shortTermMemory        = [];       // string[]  — résumés d'interactions récentes
    this.longTermKnowledge      = [];       // string[]  — réponses denses mémorisées
    this.evolutionProfile       = new EvolutionProfile();
    this.totalInteractions      = 0;
    this.evolutionScore         = 0.68;
    this.currentSpecialization  = 'Guide Polyvalent';
    this.lastAdaptation         = Date.now();

    this.#signer        = new Dilithium5Signer();
    this.#loraAdapter   = null;
    this.#trainingCount = 0;
    this.#isTraining    = false;
    this.#lossHistory   = new Float32Array(32);
    this.#exposures     = new Map();
    this.#inferenceEngine = null;
    this.#contracts     = new Map();
    this.#contractCount = 0;
  }

  // ═══════════════════════════════════════════════════════════════
  // CONNEXION AU MOTEUR T369
  // ═══════════════════════════════════════════════════════════════

  connectToInference(engine) {
    if (!engine || typeof engine.generate !== 'function') {
      throw new Error('Moteur invalide : generate() requis');
    }
    this.#inferenceEngine = engine;
    console.info('[LoraEvo] Connecté au moteur T369Inference');
  }

  // ═══════════════════════════════════════════════════════════════
  // GÉNÉRATION AVEC APPRENTISSAGE EN TEMPS RÉEL
  // ═══════════════════════════════════════════════════════════════
async generate(prompt, maxTokens = 256) {
    if (!this.#inferenceEngine) {
      throw new Error("LoraEvo n'est pas connectée au moteur d'inférence");
    }

    const enhanced = this.#buildContextualPrompt(prompt);

    let response;
    try {
      response = await this.#inferenceEngine.generate(enhanced, maxTokens);
    } catch (e) {
      console.warn('[LoraEvo] Erreur T369Inference:', e.message);
      throw e;
    }

    // Apprentissage synchrone léger — pas de LoRA ici, juste mise à jour
    // des mémoires et du profil d'évolution
    this.#learnFromInteraction(prompt, response);
    this.totalInteractions++;
    this.#adaptEvolution();

    console.debug(
      `[LoraEvo] Réponse | évolution: ${this.evolutionScore.toFixed(3)}` +
      ` | interactions: ${this.totalInteractions}` +
      ` | spéc: ${this.currentSpecialization}`
    );

    return response;
  }

  // ═══════════════════════════════════════════════════════════════
  // ENTRAÎNEMENT LOURD — vrai LoRA forward/backward sur T369
  // ═══════════════════════════════════════════════════════════════

  /**
   * @param {object} opts
   * @param {string[]} opts.lessons      — leçons textuelles
   * @param {number}   opts.epochs       — défaut 4
   * @param {number}   opts.learningRate — défaut 2e-4
   * @param {number}   opts.batchSize    — défaut 4
   */
  async train({ lessons = [], epochs = 4, learningRate = 2e-4, batchSize = 4 } = {}) {
    if (this.#isTraining) {
      return { trained: false, reason: 'Entraînement déjà en cours' };
    }
    if (lessons.length < MIN_LESSONS_TRAIN) {
      return { trained: false, reason: `Pas assez de leçons (${lessons.length} < ${MIN_LESSONS_TRAIN})` };
    }

    // Résolution du modèle T369
    const model = this.#inferenceEngine?.model ?? null;
    if (!model || typeof model.hiddenForLastToken !== 'function') {
      throw new Error(
        'Modèle T369 inaccessible. Appelle connectToInference(engine) avec un moteur chargé.'
      );
    }
    if (!model.tokenizer) {
      throw new Error('model.tokenizer non initialisé — appelle engine.loadTokenizer() avant.');
    }

    this.#isTraining = true;
    this.#trainingCount++;

    try {
      const { hiddenSize: H, vocabSize: V } = model.config;

      // Initialisation lazye de l'adapter LoRA
      if (!this.#loraAdapter || this.#loraAdapter.H !== H || this.#loraAdapter.V !== V) {
        this.#loraAdapter = new LoraAdapter(H, V, {
          rank: 8, alpha: 16, lr: learningRate, weightDecay: 1e-5,
        });
        console.info(`[LoraEvo] LoraAdapter initialisé — H=${H}, V=${V}, r=8`);
      } else {
        // Met à jour le lr si différent
        this.#loraAdapter.lr = learningRate;
      }
      const adapter = this.#loraAdapter;

      // ── Dataset — paires (contexte → token suivant) ────────
      const pairs = [];
      for (const lesson of lessons) {
        if (!lesson || lesson.length < 8) continue;
        const toks = model.tokenizer.encode(lesson.slice(0, 512));
        for (let i = 1; i < toks.length; i++) {
          pairs.push({ tokens: toks.slice(0, i), target: toks[i] });
        }
      }
      if (pairs.length === 0) throw new Error('Dataset vide après tokenization.');

      // ── Boucle d'entraînement ──────────────────────────────
      let bestLoss  = Infinity;
      let finalLoss = Infinity;
      let stagnation = 0;
      const epochLosses = [];

      for (let ep = 0; ep < epochs; ep++) {
        // Shuffle Fisher-Yates
        const idx = Array.from({ length: pairs.length }, (_, i) => i);
        for (let i = idx.length - 1; i > 0; i--) {
          const j = Math.floor(Math.random() * (i + 1));
          [idx[i], idx[j]] = [idx[j], idx[i]];
        }

        let total = 0, n = 0;

        for (let b = 0; b < idx.length; b += batchSize) {
          for (let s = b; s < Math.min(b + batchSize, idx.length); s++) {
            const { tokens, target } = pairs[idx[s]];
            let h;
            try { h = model.hiddenForLastToken(tokens); }
            catch { continue; }

            const baseLogits = model.lmHeadProject(h);
            const delta      = adapter.forward(h);
            const combined   = new Float32Array(V);
            for (let j = 0; j < V; j++) combined[j] = baseLogits[j] + delta[j];

            const { loss, dLogits } = crossEntropyGrad(combined, target);
            adapter.step(h, dLogits);
            total += loss; n++;
          }
        }

        finalLoss = n > 0 ? total / n : Infinity;
        epochLosses.push(finalLoss);
        this.#lossHistory[ep % 32] = finalLoss;

        console.debug(`[LoraEvo] Epoch ${ep + 1}/${epochs} — loss: ${finalLoss.toFixed(4)} (${n} samples)`);

        // Early stopping
        if (finalLoss >= bestLoss * LOSS_STAGNATION) {
          if (++stagnation >= 2) { console.info(`[LoraEvo] Early stopping epoch ${ep + 1}`); break; }
        } else { stagnation = 0; bestLoss = finalLoss; }
      }

      // ── Signature Dilithium5 ────────────────────────────────
      const serialized = adapter.serialize();
      const digest     = new TextEncoder().encode(
        `loraevo_v${this.#trainingCount}_${Date.now()}_${finalLoss.toFixed(6)}`
      );
      const signature = this.#signer.sign(digest);

      // ── Checkpoint ─────────────────────────────────────────
      const meta = {
        version: this.#trainingCount, timestamp: Date.now(),
        finalLoss, bestLoss, epochs: epochLosses.length, epochLosses,
        pairs: pairs.length, lessons: lessons.length,
        signature: Array.from(signature.subarray(0, 64)),
      };
      await this.#persistCheckpoint(`loraevo_v${this.#trainingCount}`, meta, serialized);

      // Boost évolution suite à l'entraînement
      this.evolutionScore = Math.min(0.99, this.evolutionScore + 0.012 * epochLosses.length);
      this.evolutionProfile.wisdom = Math.min(0.99, this.evolutionProfile.wisdom + 0.008);

      console.info(
        `[LoraEvo] ✅ Training #${this.#trainingCount} — ` +
        `loss: ${finalLoss.toFixed(4)} | best: ${bestLoss.toFixed(4)} | sig: ${signature.length}B`
      );

      return {
        trained: true, lessons: lessons.length, pairs: pairs.length,
        finalLoss, bestLoss, epochs: epochLosses.length, epochLosses,
        signatureBytes: signature.length,
        checkpointId: `loraevo_v${this.#trainingCount}`,
        adapterParams: adapter.numParams(),
      };

    } finally {
      this.#isTraining = false;
    }
  }

  // ═══════════════════════════════════════════════════════════════
  // MÉTHODES PRIVÉES
  // ═══════════════════════════════════════════════════════════════

  #buildContextualPrompt(prompt) {
    const ctx = this.shortTermMemory.length > 0
      ? '\n[Contexte récent]:\n' +
        this.shortTermMemory.slice(-4).map(e => `- ${e}`).join('\n') + '\n'
      : '';

    const profile = this.evolutionProfile.toJSON();
    const profileLine =
      `[Profil] Spécialisation: ${this.currentSpecialization} | ` +
      `Évolution: ${this.evolutionScore.toFixed(2)} | ` +
      `Sagesse: ${profile.wisdom} | Éthique: ${profile.ethics}`;

    return (
      'Tu es LoraEvo, un assistant intelligent, bienveillant et auto-évolutif de SkyAInet.\n' +
      'Tu apprends en continu et t\'adaptes à l\'utilisateur.\n\n' +
      `${ctx}${profileLine}\n` +
      `Utilisateur : ${prompt}\nLoraEvo :`
    );
  }

  #learnFromInteraction(prompt, response) {
    // Mémoire court-terme — résumé compact
    const snippet = typeof response === 'string' ? response.slice(0, 80) : String(response).slice(0, 80);
    this.shortTermMemory.push(`Q: ${prompt.slice(0, 60)} | R: ${snippet}`);
    if (this.shortTermMemory.length > STM_MAX) this.shortTermMemory.shift();

    // Mémoire long-terme — uniquement les réponses denses
    const full = typeof response === 'string' ? response : '';
    if (full.length > LTM_MIN_CHARS) {
      this.longTermKnowledge.push(full);
      if (this.longTermKnowledge.length > LTM_MAX) this.longTermKnowledge.shift();
    }

    // Détection de spécialisation avec compteurs d'exposition cumulés
    const spec = detectSpecialization(prompt, this.#exposures);
    this.#exposures.set(spec, (this.#exposures.get(spec) ?? 0) + 1);
    this.currentSpecialization = spec;

    // Adaptation du profil selon la spécialisation
    this.evolutionProfile.adapt(spec);
    this.lastAdaptation = Date.now();
  }

  #adaptEvolution() {
    if (this.totalInteractions % EVOLVE_EVERY === 0) {
      this.evolutionScore = Math.min(0.99, this.evolutionScore + EVOLVE_BOOST);
    }
  }

  async #persistCheckpoint(key, meta, weights) {
    try {
      await mkdir(CHECKPOINT_DIR, { recursive: true });
      await writeFile(`${CHECKPOINT_DIR}/${key}.json`, JSON.stringify(meta));
      if (weights instanceof Uint8Array) {
        await writeFile(`${CHECKPOINT_DIR}/${key}.bin`, weights);
      }
      return;
    } catch { /* Pas dans Node ou accès refusé */ }

    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.setItem(key, JSON.stringify(meta));
      }
    } catch { /* localStorage indisponible */ }
  }

  // ═══════════════════════════════════════════════════════════════
  // SMART CONTRACT GENERATOR
  //
  // LoraÉvo génère des Smart Contracts Solidity à la demande.
  // Philosophie : comme Thevie crée des nœuds automatiquement,
  // LoraÉvo crée des Smart Contracts automatiquement.
  //
  // Types supportés :
  //   ERC20        — Token fongible (taxe, vesting, mint/burn)
  //   NFT          — ERC721 avec metadata, royalties, whitelist
  //   DAO          — Gouvernance + vote + quorum + timelock
  //   Vesting      — Vesting linéaire/clifff multi-bénéficiaires
  //   Staking      — Staking avec rewards APY configurable
  //   Marketplace  — Achat/vente NFT + frais plateforme
  //   MultiSig     — Portefeuille multi-signatures N-of-M
  //
  // Coût SKY par génération (selon complexité) :
  //   Simple   → 2 SKY
  //   Standard → 5 SKY
  //   Complex  → 12 SKY
  // ═══════════════════════════════════════════════════════════════

  /**
   * Génère un Smart Contract Solidity à partir d'une description.
   *
   * @param {string} description   — Description en langage naturel
   * @param {object} options
   * @param {string}  options.type          — Type de contrat (voir liste ci-dessus)
   * @param {string}  options.network       — 'testnet' | 'mainnet' | 'local'
   * @param {boolean} options.audit         — Activer l'audit de sécurité
   * @param {boolean} options.deploy        — Déployer automatiquement après génération
   * @param {number}  options.taxPercent    — Taxe en % (ERC20)
   * @param {number}  options.vestingMonths — Durée vesting en mois
   * @param {number}  options.totalSupply   — Supply totale (ERC20)
   * @param {string}  options.tokenName     — Nom du token
   * @param {string}  options.tokenSymbol   — Symbole du token
   * @param {number}  options.royaltyPercent— Royalties % (NFT)
   * @param {number}  options.signaturesRequired — Seuil multi-sig
   * @param {number}  options.apyPercent    — APY staking
   * @returns {Promise<GeneratedContract>}
   */
  async generateSmartContract(description, options = {}) {
    if (!description?.trim()) throw new Error('Description requise');

    const type    = (options.type ?? 'ERC20').toUpperCase();
    const network = options.network ?? 'testnet';
    const audit   = options.audit !== false;

    // Vérifier le type supporté
    const SUPPORTED = ['ERC20','NFT','DAO','VESTING','STAKING','MARKETPLACE','MULTISIG'];
    if (!SUPPORTED.includes(type)) {
      throw new Error(`Type '${type}' non supporté. Types valides : ${SUPPORTED.join(', ')}`);
    }

    console.info(`[LoraEvo] Génération Smart Contract ${type} sur ${network}…`);
    this.evolutionProfile.adapt('smart_contract_generation');

    // Sélectionner le template
    const template  = SC_TEMPLATES[type];
    const params    = this.#extractContractParams(description, options, type);
    const code      = this.#renderTemplate(template, params);
    const complexity = this.#assessComplexity(type, options);
    const skyFee    = { simple: 2, standard: 5, complex: 12 }[complexity];

    // Audit de sécurité
    const auditReport = audit ? this.#auditContract(code, type) : null;

    // Signature Dilithium5 du code
    const codeBytes   = new TextEncoder().encode(code);
    const signature   = Buffer.from(this.#signer.sign(codeBytes)).toString('hex').slice(0, 64);

    // ABI simplifié (basé sur le type)
    const abi = SC_ABI_TEMPLATES[type] ?? [];

    // Construire l'objet contrat
    this.#contractCount++;
    const contractId = `sc_${type.toLowerCase()}_${Date.now()}_${this.#contractCount}`;
    const contract = {
      id            : contractId,
      name          : params.tokenName ?? params.contractName ?? `${type}_${this.#contractCount}`,
      type,
      network,
      description   : description.trim(),
      params,
      code,
      abi,
      bytecode      : `0x${this.#fakeBytecode(code)}`,  // simulé — vrai compile en prod
      auditReport,
      signature,
      complexity,
      skyFee,
      deployStatus  : 'generated',
      deployedAt    : null,
      contractAddress: null,
      createdAt     : Date.now(),
      generatedBy   : 'LoraEvo',
    };

    // Stocker dans la Map interne
    this.#contracts.set(contractId, contract);

    // Déploiement automatique si demandé
    if (options.deploy) {
      await this.deployContract(contractId);
    }

    this.totalInteractions++;
    console.info(`[LoraEvo] Contrat généré : ${contractId} | ${complexity} | ${skyFee} SKY`);
    return contract;
  }

  /**
   * Déploie un contrat généré sur le réseau configuré.
   * En production : appel viem createWalletClient + deployContract.
   * En mode démo : simule un déploiement avec une adresse factice.
   *
   * @param {string} contractId
   * @returns {Promise<{ contractAddress, txHash, deployedAt }>}
   */
  async deployContract(contractId) {
    const contract = this.#contracts.get(contractId);
    if (!contract) throw new Error(`Contrat '${contractId}' introuvable`);
    if (contract.deployStatus === 'deployed') throw new Error('Contrat déjà déployé');

    console.info(`[LoraEvo] Déploiement ${contractId} sur ${contract.network}…`);

    // Simulation du déploiement (en production : viem deployContract)
    await new Promise(r => setTimeout(r, 800));
    const fakeAddress = `0x${Array.from({ length: 40 }, () =>
      Math.floor(Math.random() * 16).toString(16)).join('')}`;
    const fakeTxHash  = `0x${Array.from({ length: 64 }, () =>
      Math.floor(Math.random() * 16).toString(16)).join('')}`;

    contract.deployStatus    = 'deployed';
    contract.contractAddress = fakeAddress;
    contract.deployedAt      = Date.now();
    contract.txHash          = fakeTxHash;

    console.info(`[LoraEvo] Déployé : ${fakeAddress} (tx: ${fakeTxHash.slice(0,18)}…)`);
    return { contractAddress: fakeAddress, txHash: fakeTxHash, deployedAt: contract.deployedAt };
  }

  /** Retourne tous les contrats générés. */
  listContracts() {
    return [...this.#contracts.values()].map(c => ({
      id             : c.id,
      name           : c.name,
      type           : c.type,
      network        : c.network,
      complexity     : c.complexity,
      skyFee         : c.skyFee,
      deployStatus   : c.deployStatus,
      contractAddress: c.contractAddress,
      deployedAt     : c.deployedAt,
      createdAt      : c.createdAt,
    }));
  }

  /** Retourne un contrat complet avec son code Solidity. */
  getContract(contractId) {
    return this.#contracts.get(contractId) ?? null;
  }

  /** Supprime un contrat de la liste locale. */
  deleteContract(contractId) {
    if (!this.#contracts.has(contractId)) throw new Error('Contrat introuvable');
    this.#contracts.delete(contractId);
  }

  // ─── Helpers privés ───────────────────────────────────────────
/** Extrait les paramètres structurés de la description + options. */
  #extractContractParams(description, options, type) {
    const desc = description.toLowerCase();
    return {
      tokenName     : options.tokenName    ?? this.#extractToken(desc, 'name')    ?? 'SkyToken',
      tokenSymbol   : options.tokenSymbol  ?? this.#extractToken(desc, 'symbol')  ?? 'SKT',
      totalSupply   : options.totalSupply  ?? this.#extractNumber(desc, ['supply','total']) ?? 1_000_000,
      taxPercent    : options.taxPercent   ?? this.#extractNumber(desc, ['tax','taxe','fee']) ?? 0,
      vestingMonths : options.vestingMonths ?? this.#extractNumber(desc, ['vesting','mois','months']) ?? 12,
      royaltyPercent: options.royaltyPercent ?? this.#extractNumber(desc, ['royalt','royal']) ?? 5,
      signaturesRequired: options.signaturesRequired ?? 2,
      totalSigners  : options.totalSigners ?? 3,
      apyPercent    : options.apyPercent   ?? this.#extractNumber(desc, ['apy','reward','rendement']) ?? 12,
      quorumPercent : options.quorumPercent ?? 51,
      contractName  : options.contractName ?? `${type}Contract`,
      mintable      : desc.includes('mint') || options.mintable === true,
      burnable      : desc.includes('burn') || options.burnable === true,
      pausable      : desc.includes('paus') || options.pausable === true,
      whitelist     : desc.includes('whitelist') || desc.includes('liste blanche'),
      description   : description.trim(),
    };
  }

  /** Cherche un nombre dans la description associé à des mots-clés. */
  #extractNumber(text, keywords) {
    for (const kw of keywords) {
      const m = text.match(new RegExp(`(\\d+(?:\\.\\d+)?)\\s*%?\\s*(?:de\\s+)?${kw}|${kw}\\s+(?:de\\s+)?(\\d+(?:\\.\\d+)?)`));
      if (m) return parseFloat(m[1] ?? m[2]);
    }
    return null;
  }

  /** Cherche un nom/symbole de token dans la description. */
  #extractToken(text, type) {
    if (type === 'symbol') {
      const m = text.match(/\b([A-Z]{2,6})\b/);
      return m ? m[1] : null;
    }
    const m = text.match(/(?:token|coin|called?|nommé)\s+["']?([A-Za-z][A-Za-z0-9 ]{1,20})["']?/i);
    return m ? m[1].trim() : null;
  }

  /** Évalue la complexité du contrat. */
  #assessComplexity(type, options) {
    const complexTypes = ['DAO','MARKETPLACE','MULTISIG'];
    const standardTypes = ['VESTING','STAKING','NFT'];
    if (complexTypes.includes(type)) return 'complex';
    if (standardTypes.includes(type)) return 'standard';
    if (options.taxPercent > 0 || options.vestingMonths > 0) return 'standard';
    return 'simple';
  }

  /** Génère un bytecode factice basé sur un hash du code. */
  #fakeBytecode(code) {
    let h = 0;
    for (let i = 0; i < code.length; i++) h = (Math.imul(31, h) + code.charCodeAt(i)) | 0;
    return Math.abs(h).toString(16).padStart(8, '0').repeat(8);
  }

  /** Remplace les variables {{PARAM}} dans le template. */
  #renderTemplate(template, params) {
    return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
      const val = params[key];
      return val !== undefined ? String(val) : `/* ${key} */`;
    });
  }

  /**
   * Audit de sécurité basique — vérifie les patterns dangereux.
   * En production : intégration Slither ou Mythril via API.
   */
  #auditContract(code, type) {
    const issues = [];

    if (!code.includes('pragma solidity')) {
      issues.push({ severity: 'HIGH', rule: 'MISSING_PRAGMA', message: 'pragma solidity manquant' });
    }
    if (code.includes('tx.origin')) {
      issues.push({ severity: 'HIGH', rule: 'TX_ORIGIN', message: 'tx.origin utilisé — risque phishing' });
    }
    if (code.includes('block.timestamp') && !code.includes('// timestamp-safe')) {
      issues.push({ severity: 'MEDIUM', rule: 'TIMESTAMP_DEP', message: 'Dépendance block.timestamp — manipulable par les mineurs' });
    }
    if (!code.includes('ReentrancyGuard') && (type === 'STAKING' || type === 'MARKETPLACE')) {
      issues.push({ severity: 'HIGH', rule: 'REENTRANCY', message: 'Pas de protection ReentrancyGuard pour un contrat financier' });
    }
    if (!code.includes('Ownable') && !code.includes('AccessControl')) {
      issues.push({ severity: 'LOW', rule: 'NO_ACCESS_CONTROL', message: 'Aucun contrôle d\'accès détecté' });
    }
    if (code.includes('selfdestruct')) {
      issues.push({ severity: 'MEDIUM', rule: 'SELFDESTRUCT', message: 'selfdestruct présent — risque de perte de fonds' });
    }

    const highCount   = issues.filter(i => i.severity === 'HIGH').length;
    const mediumCount = issues.filter(i => i.severity === 'MEDIUM').length;
    const score       = Math.max(0, 100 - highCount * 25 - mediumCount * 10 - issues.length * 2);

    return {
      score,
      grade  : score >= 90 ? 'A' : score >= 75 ? 'B' : score >= 60 ? 'C' : 'D',
      issues,
      summary: `${issues.length} issue(s) — Score: ${score}/100`,
      auditedAt: Date.now(),
    };
  }

  // ═══════════════════════════════════════════════════════════════
  // API PUBLIQUE
  // ═══════════════════════════════════════════════════════════════

  getStatus() {
    return (
      `LoraEvo | Évolution: ${this.evolutionScore.toFixed(3)}` +
      ` | Interactions: ${this.totalInteractions}` +
      ` | Spécialisation: ${this.currentSpecialization}` +
      ` | Mémoire: ${this.shortTermMemory.length} court / ${this.longTermKnowledge.length} long` +
      ` | Adapter: ${this.#loraAdapter ? `${this.#loraAdapter.numParams()} params` : 'non init'}`
    );
  }

  getEvolutionProfile() { return this.evolutionProfile.toJSON(); }

  getStats() {
    const filled  = Math.min(this.#trainingCount * 4, 32);
    let   lossAvg = 0;
    for (let i = 0; i < filled; i++) lossAvg += this.#lossHistory[i];
    return {
      totalInteractions    : this.totalInteractions,
      evolutionScore       : +this.evolutionScore.toFixed(4),
      currentSpecialization: this.currentSpecialization,
      trainingCount        : this.#trainingCount,
      isTraining           : this.#isTraining,
      adapterParams        : this.#loraAdapter?.numParams() ?? 0,
      avgLoss              : filled > 0 ? +(lossAvg / filled).toFixed(4) : null,
      exposures            : Object.fromEntries(this.#exposures),
      profile              : this.evolutionProfile.toJSON(),
      engineConnected      : !!this.#inferenceEngine,
      // Smart Contracts
      contractsGenerated   : this.#contractCount,
      contractsDeployed    : [...this.#contracts.values()].filter(c => c.deployStatus === 'deployed').length,
    };
  }

  // ─── Bridge poids vivants → swarm d'adapters (Fusion L2) ──────

  /** Expose l'adapter LoRA entraîné (ou null). */
  getAdapter() { return this.#loraAdapter; }

  /**
   * Enregistre l'adapter entraîné comme entrée du Dynamic Adapter Swarm
   * (model_registry) → découvrable + hot-swappable (boucle des poids vivants :
   * l'entraînement de LoraÉvo nourrit le routing L0).
   * @param {object} registry — ModelRegistry
   * @param {string} [name]
   */
  registerInSwarm(registry, name = `loraevo-v${this.#trainingCount}`) {
    if (!registry || typeof registry.registerAdapter !== 'function')
      throw new Error('registry.registerAdapter requis');
    registry.registerAdapter({
      name, task: 'code', runner: 'loraevo', source: 'lesson', baseModel: 'loraevo',
      rank: this.#loraAdapter?.rank ?? 8, version: this.#trainingCount,
      specialties: ['code', 'contracts', 'web', 'governance'],
    });
    return name;
  }

  /**
   * Test-Time Training explicite : entraîne sur les connaissances accumulées
   * pendant la session (mémoire long-terme + court-terme).
   */
  async trainOnRecent(opts = {}) {
    const lessons = [...this.longTermKnowledge, ...this.shortTermMemory]
      .filter(l => typeof l === 'string' && l.length >= 8);
    return this.train({ lessons, ...opts });
  }
}

export default LoraEvo;
export { SC_TEMPLATES, SC_ABI_TEMPLATES };